#!/bin/bash
#SBATCH --partition=GPU
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=3:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=12           
#SBATCH --mem=80G                
#SBATCH --job-name=test
##SBATCH --gres=gpu:1 



#source /etc/profile.d/modules.sh
#module use /opt/nvidia/hpc_sdk/modulefiles/
#module load nvhpc

source /u/area/ddoimo/anaconda3/bin/activate ./env_v100

export OMP_NUM_TREADS=12

srun -N1 python src/run.py  --data_dir igpt_models  --ckpt_dir igpt_models  --model "s" \
                        --results_dir "./results"  --nimg_cat 300   --n_sub_batch 64 
