#!/bin/bash
#SBATCH --partition=DGX
#SBATCH --account=lade
#SBATCH --nodes=1
#SBATCH --time=3:00:00            
#SBATCH --ntasks-per-node=1       
#SBATCH --cpus-per-task=24           
#SBATCH --mem=120G                
#SBATCH --job-name=test
##SBATCH --gres=gpu:1 

source /u/area/ddoimo/anaconda3/bin/activate ./env_amd

export OMP_NUM_TREADS=12

srun -N1 python src/run.py  --data_dir igpt_models  --ckpt_dir igpt_models  --model "s" \
                        --results_dir "./results"  --nimg_cat 300   --n_sub_batch 64 